#!/usr/bin/with-contenv bash

echo "waiting for minio service to start"
s6-svwait -u /var/run/s6/services/minio

# tell s6 to only run this script once
s6-svc -O /var/run/s6/services/minio-config

# wait until minio is "Ready" - https://github.com/minio/minio/pull/5647
while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://localhost:9000/minio/health/ready)" != "200" ]]; do sleep 5; done

mc --version

# authenticate to minio storage
mc config host add minio http://localhost:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} --api S3v4
mc admin info minio

# (Re)Set public readonly bucket policy on  buckets
mc policy set none minio/thumbnails
mc policy set none minio/documents

mc policy set download minio/thumbnails
mc policy set download minio/documents


