#!/usr/bin/with-contenv bash

echo "waiting for minio service to start"
s6-svwait -u /var/run/s6/services/minio

# tell s6 to only run this script once
s6-svc -O /var/run/s6/services/minio-config

# wait until minio is "Ready" - https://github.com/minio/minio/pull/5647
while [[ "$(curl -s -o /dev/null -w ''%{http_code}'' http://storage:9000/minio/health/ready)" != "200" ]]; do sleep 5; done

mc --version

# authenticate to minio storage
mc config host add minio http://storage:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} --api S3v4
mc admin info minio

# (Re)Set public readonly bucket policy on  buckets
mc policy set none minio/thumbnails
mc policy set none minio/documents

mc policy set download minio/thumbnails
mc policy set download minio/documents

# set the notification system to AMQP
#mc admin config set minio/ notify_amqp:1 exchange="lodestone" exchange_type="fanout" mandatory="false" no_wait="false"  url="amqp://lodestone:lodestone@rabbitmq:5672" auto_deleted="false" delivery_mode="0" durable="false" internal="false" routing_key="storagelogs"
#mc admin service restart minio

# (Re)Set event watcher on documents bucket
#mc event add minio/documents arn:minio:sqs::1:amqp -p --event put,delete


