#!/usr/bin/with-contenv bash

echo "waiting for minio service to start"
s6-svwait -u /var/run/s6/services/minio

# tell s6 to only run this script once
s6-svc -O /var/run/s6/services/minio-config

mc --version

# authenticate to minio storage
mc config host add minio http://storage:9000 ${MINIO_ACCESS_KEY} ${MINIO_SECRET_KEY} --api S3v4
mc admin info server minio

# (Re)Set public readonly bucket policy on  buckets
mc policy set none minio/thumbnails
mc policy set none minio/documents

mc policy set download minio/thumbnails
mc policy set download minio/documents

# (Re)Set event watcher on documents bucket
mc event add minio/documents arn:minio:sqs::1:amqp -p --event put,post,delete


