#!/usr/bin/with-contenv bash

if [ ! -z "$DISABLE_FRONTEND" ]; then
    # hack: this is run-once service
    # stop the s6-supervise process and ensure that its not started again
    s6-svc -x /var/run/s6/services/frontend
    rm -rf /var/run/s6/services/frontend
    exit 0
fi


cd /lodestone/frontend
rm -rf node_modules
npm install

# in dev mode we need to make sure we dont accidentally commit files in the public directory
echo "*" > /lodestone/backend/public/.gitignore
npm run-script dev-lodestone


