#!/usr/bin/with-contenv bash

echo "waiting for minio service to start"
s6-svwait -u /var/run/s6/services/minio

ls -alt /usr/bin/lodestone-fs-publisher
/usr/bin/lodestone-fs-publisher start \
--amqp-url="amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${LS_RABBITMQ_HOST}:${LS_RABBITMQ_PORT}" \
--dir=/data/documents \
--bucket=documents
