#!/usr/bin/with-contenv bash

ls -alt /usr/bin/lodestone-thumbnail-processor
/usr/bin/lodestone-thumbnail-processor start \
--amqp-url="amqp://${RABBITMQ_USER}:${RABBITMQ_PASS}@${LS_RABBITMQ_HOST}:${LS_RABBITMQ_PORT}" \
--storage-endpoint="http://${LS_STORAGE_HOST}:${LS_STORAGE_PORT}" \
${DEBUG:+--debug}
